version: "3.8"

services:
  db:
    container_name: db
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secretpassword
      MYSQL_DATABASE: librairie_digital
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: secretpassword

  phpmyadmin:
    container_name: pma
    image: phpmyadmin:latest
    restart: always
    ports:
      - "3306:80"
    links:
      - db
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_ARBITRARY=1
      - PMA_USER=dbuser
      - PMA_PASSWORD=secretpassword

  php:
    container_name: php
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ../:/var/www/librairie_digital
    depends_on:
      - db

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8000:80'
    volumes:
      - ../:/var/www/librairie_digital
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php